# -*- coding: utf-8 -*-
"""HYPOTHESIS_TESTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnDPgWzF91n1XwXRONQjqRj0BEePlX1v
"""

# Hypothesis Test — Bombay hospitality Ltd. weekly operating cost

import numpy as np
import scipy.stats as stats

x_bar = 3050.0
n = 25
X_mean = 600.0
unit_sd = 25.0
mu_theoretical = 1000 + 5 * X_mean

sigma = 5 * unit_sd

# Significance level
alpha = 0.05


print("1) Hypotheses:")
print(f"   H0: μ = {mu_theoretical:.2f}  (or μ <= {mu_theoretical:.2f})")
print(f"   H1: μ > {mu_theoretical:.2f}\n")

# 2) Test statistic (z) because population sd is known
# formula: z = (x_bar - mu) / (sigma / sqrt(n))
se = sigma / np.sqrt(n)
z_stat = (x_bar - mu_theoretical) / se

print("2) Test Statistic:")
print(f"   Sample mean (x̄)          = {x_bar:.2f}")
print(f"   Theoretical mean (μ0)    = {mu_theoretical:.2f}")
print(f"   Population sd (σ)        = {sigma:.2f}")
print(f"   Standard error (σ/√n)    = {se:.4f}")
print(f"   Test statistic (z)       = {z_stat:.4f}\n")

# 3) Critical value from standard normal for alpha = 0.05 (one-tailed, right side)
z_critical = stats.norm.ppf(1 - alpha)   # for right-tailed test
print("3) Critical Value (one-tailed, α = 0.05):")
print(f"   z_critical = {z_critical:.4f}\n")

# 4) Decision: compare z_stat to z_critical
print("4) Decision:")
if z_stat > z_critical:
    print("   Since z_stat > z_critical, we REJECT H0 in favor of H1.")
else:
    print("   Since z_stat <= z_critical, we DO NOT REJECT H0.")

# Also compute p-value for additional evidence
# For right-tailed test, p-value = 1 - Phi(z_stat)
p_value = 1 - stats.norm.cdf(z_stat)
print(f"   p-value = {p_value:.6f}\n")

# 5) Conclusion
print("5) Conclusion:")
if z_stat > z_critical:
    print("   There is sufficient evidence at α = 0.05 to conclude that weekly operating costs are higher than the model suggests.")
else:
    print("   There is NOT sufficient evidence at α = 0.05 to conclude that weekly operating costs are higher than the model suggests.")
    print("   In fact, the sample mean is considerably LOWER than the theoretical mean, so the owners' claim is not supported by this sample.")

# Print a short summary
print("\nSummary (numeric):")
print(f"   Theoretical mean (μ0) = {mu_theoretical:.2f}")
print(f"   Sample mean (x̄)       = {x_bar:.2f}")
print(f"   z statistic            = {z_stat:.4f}")
print(f"   z critical (α=0.05)    = {z_critical:.4f}")
print(f"   p-value                = {p_value:.6f}")